#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

# PROJECT_NAME := iot-home-project

include $(IDF_PATH)/make/project.mk

CFLAGS+=-D LOCATION=${LOCATION}